# User permissions
APPROVE_USER_REQUEST = "APPROVE_USER_REQUEST"
APPROVE_USERS = "APPROVE_USERS"
CREATE_USER = "CREATE_USER"
DISABLE_USER = "DISABLE_USER"
ENABLE_USER = "ENABLE_USER"
LIST_USERS = "LIST_USERS"
MODIFY_USER = "MODIFY_USER"
VIEW_USER_DETAILS = "VIEW_USER_DETAILS"

# Role permissions
APPROVE_ROLE_REQUEST = "APPROVE_ROLE_REQUEST"
CREATE_ROLE = "CREATE_ROLE"
DISABLE_ROLE = "DISABLE_ROLE"
ENABLE_ROLE = "ENABLE_ROLE"
LIST_ROLES = "LIST_ROLES"
MODIFY_ROLE = "MODIFY_ROLE"
VIEW_ROLE_DETAILS = "VIEW_ROLE_DETAILS"

# Config engine permissions
MANAGE_SOD_CONFIG = "MANAGE_SOD_CONFIG"
MANAGE_SECURITY_CONFIG = "MANAGE_SECURITY_CONFIG"