UPDATED_AT_CHOICES_ENUMS = (
    ("A_WEEK", "A_WEEK"),
    ("A_MONTH", "A_MONTH"),
    ("3_MONTH", "3_MONTH"),
    ("6_MONTH", "6_MONTH"),
    ("A_YEAR", "A_YEAR"),
)

STATE_CHOICES_ENUMS = (
    ("INACTIVE", "INACTIVE"),
    ("ACTIVE", "ACTIVE")
)

LEDGER_STATE_CHOICES_ENUMS = (
    ("CLOSED", "CLOSED"),
    ("OPEN", "OPEN")
)

ACTIVITY_LOG_ACTION_TYPE_ENUMS = (
    ("INITIATION", "INITIATION"),
    ("APPROVAL", "APPROVAL"),
    ("REJECTION", "REJECTION"),
    ("MODIFICATION", "MODIFICATION")
)

INITIATED_BY_FILTER_CHOICES_ENUMS = (
    ("ME", "ME"),
    ("MY_TEAM", "MY_TEAM"),
    ("SYSTEM_WIDE", "SYSTEM_WIDE"),
)

APPROVED_BY_FILTER_CHOICES_ENUMS = (
    ("ME", "ME"),
    ("MY_TEAM", "MY_TEAM"),
    ("SYSTEM_WIDE", "SYSTEM_WIDE"),
)

REQUEST_TYPE_ENUMS = (
    ("MODIFICATION", "MODIFICATION"),
    ("CREATION", "CREATION"),
    ("DEACTIVATION", "DEACTIVATION"),
    ("REACTIVATION", "REACTIVATION"),
    ("CONFIGURATION", "CONFIGURATION")
)
