from dataclasses import dataclass


@dataclass
class PERMISSIONS:
    # User permissions
    APPROVE_USER_REQUEST = "APPROVE_USER_REQUEST"
    CREATE_USER = "CREATE_USER"
    DISABLE_USER = "DISABLE_USER"
    ENABLE_USER = "ENABLE_USER"
    LIST_USERS = "LIST_USERS"
    MODIFY_USER = "MODIFY_USER"
    VIEW_USER_DETAILS = "VIEW_USER_DETAILS"

    # Role permissions
    APPROVE_ROLE_REQUEST = "APPROVE_ROLE_REQUEST"
    CREATE_ROLE = "CREATE_ROLE"
    DISABLE_ROLE = "DISABLE_ROLE"
    ENABLE_ROLE = "ENABLE_ROLE"
    LIST_ROLES = "LIST_ROLES"
    MODIFY_ROLE = "MODIFY_ROLE"
    VIEW_ROLE_DETAILS = "VIEW_ROLE_DETAILS"

    # Config engine permissions
    MANAGE_SOD_CONFIG = "MANAGE_SOD_CONFIG"
    MANAGE_SECURITY_CONFIG = "MANAGE_SECURITY_CONFIG"

    # Fiscal Period permissions
    APPROVE_FISCAL_PERIOD_REQUEST = "APPROVE_FISCAL_PERIOD_REQUEST"
    CREATE_FISCAL_PERIOD = "CREATE_FISCAL_PERIOD"
    DISABLE_FISCAL_PERIOD = "DISABLE_FISCAL_PERIOD"
    ENABLE_FISCAL_PERIOD = "ENABLE_FISCAL_PERIOD"
    LIST_FISCAL_PERIOD = "LIST_FISCAL_PERIOD"
    MODIFY_FISCAL_PERIOD = "MODIFY_FISCAL_PERIOD"
    VIEW_FISCAL_PERIOD_DETAILS = "VIEW_FISCAL_PERIOD_DETAILS"

    # Currency permissions
    APPROVE_CURRENCY_REQUEST = "APPROVE_CURRENCY_REQUEST"
    CREATE_CURRENCY = "CREATE_CURRENCY"
    DISABLE_CURRENCY = "DISABLE_CURRENCY"
    ENABLE_CURRENCY = "ENABLE_CURRENCY"
    LIST_CURRENCY = "LIST_CURRENCY"
    MODIFY_CURRENCY = "MODIFY_CURRENCY"
    VIEW_CURRENCY_DETAILS = "VIEW_CURRENCY_DETAILS"

    # Ledger Permissions
    APPROVE_LEDGER_REQUEST = "APPROVE_LEDGER_REQUEST"
    CREATE_LEDGER = "CREATE_LEDGER"
    DISABLE_LEDGER = "DISABLE_LEDGER"
    ENABLE_LEDGER = "ENABLE_LEDGER"
    LIST_LEDGER = "LIST_LEDGER"
    MODIFY_LEDGER = "MODIFY_LEDGER"
    VIEW_LEDGER_DETAILS = "VIEW_LEDGER_DETAILS"

    # Journal Posting Permissions
    APPROVE_JOURNAL_POSTING_REQUEST = "APPROVE_JOURNAL_POSTING_REQUEST"
    CREATE_JOURNAL_POSTING = "CREATE_JOURNAL_POSTING"
    DISABLE_JOURNAL_POSTING = "DISABLE_JOURNAL_POSTING"
    ENABLE_JOURNAL_POSTING = "ENABLE_JOURNAL_POSTING"
    LIST_JOURNAL_POSTING = "LIST_JOURNAL_POSTING"
    MODIFY_JOURNAL_POSTING = "MODIFY_JOURNAL_POSTING"
    VIEW_JOURNAL_POSTING_DETAILS = "VIEW_JOURNAL_POSTING_DETAILS"
